### PR TITLE
Playing sounds on mention.

### PR DESCRIPTION
**Pull request by LynnCinnamon**
Implemented sound loading / play.

### CODE REVIEW

**Review by TheExkaliburg — CHANGES_REQUESTED** [review]
If i understand the stuff right you save the sounds in the module sounds.js, i would advise to use the store (vuex) to keep this stuff in line with all the other data being saved. Also a volume slider is really needed for this one.

- [x] Volume Slider
- [x] Change sound.js to a store module

**Comment by LynnCinnamon** [comment]
If I understand correctly, the store does add a bit of overhead and is mainly useful for the reactivity (reacting to changes in variables) the sounds do not use this at all and would only take the  performance hit due to the overhead in the store. If you wish it to be in the store, I can do that but I think it is not advisable to put all data we save in there but only the data that we need to react to if changed.

**Comment by TheExkaliburg** [comment]
it didn't add that much overhead, the overhead i thought it added was caused by the worst case resorting of the whole ladder i explained a few weeks ago until eta found i sorted it the wrong way ^^

**Review by TheExkaliburg — APPROVED** [review]
Would love to see the sounds in the optionsModule or the sounds reworked as the soundModule, but this is good enough for now, the rest should be refactored a bit if possible or I'm gonna go over it in a bit of time 👍

**Pull request merged**
